"""Do the factor families this repository never examined add an *engine*?

[Decision 0005](../../../../docs/decisions/0005-factor-premia-closed-on-public-data.md)
closed factor work "on public data" on the strength of five families — HML, RMW, CMA,
UMD, SMB — against the eighteen in :data:`EQUITY_FACTOR_FAMILIES`. Seven of the untested ones
have free monthly data already reachable from the adapters in
:mod:`portfolio_edge.data`: betting against beta, quality, short- and long-term
reversal, accruals, net issuance, and the unlevered low-beta decile spread. This
module is the arithmetic that scores them.

**The question is breadth, not premia, and the two have very different resolution.**
A premium is a mean, and [the evidence base](../../../../docs/research/evidence-base.md)
§1 measures this library's floor for one at 2.62 pp/yr pooled and 5.0 pp/yr for a
single US post-publication window — above the 2.0 pp/yr that would matter. A
correlation is not a mean. Over 700 monthly observations a correlation near zero has a
standard error near ``1/sqrt(700) = 0.038``, so the *same files that cannot sign a
premium can resolve a correlation to two decimal places*. That asymmetry is why this
module reports both and why the conclusions it licenses are about the correlation
matrix rather than about any expected return.

**What clears, clears as an overlay.** Admission is equation (4) of
:mod:`portfolio_edge.studies.overlay_growth`, ``S_d > L rho sigma_p``, and that module's
own warning applies here with force: the condition is a first-order statement at
``w = 0`` and is **not** a decision rule above roughly ``|rho| = 0.5``. The unlevered
low-beta decile spread sits well past that boundary and is scored, and reported, as
inadmissible-to-this-test rather than as passing or failing it.

**Three properties of the inputs decide how far any of it may be read.**

*They are gross long-short academic portfolios.* Every series here is
zero-net-investment, has no fee, no spread, no borrow, no capacity and no tax, and the
short leg is assumed free. A premium is not a sleeve; a sleeve needs a vehicle, and
whether one exists is a fact about the fund shelf rather than about the premium.

*Two of them are vendor reconstructions by a firm that sells the strategy.* The BAB
and QMJ workbooks are rebuilt from scratch on every update, publish no vintage archive
and state no cost basis anywhere — the same flags the time-series-momentum file carries
and the same reason [Experiment 011](../../../experiments/exp_011_overlay_stack.yaml)
returned ``unresolved``.

*Three of them do not exist as published factors at all.* Ken French distributes
sorted portfolios for net issuance, accruals and prior beta but no long-short factor
file for any of them, so those three spreads are **this repository's construction**.
They inherit no external replication and must never be quoted as "the Ken French
accruals factor".

Nothing here reads market data; the caller supplies aligned arrays. The tables are
regenerated by :mod:`portfolio_edge.studies._factor_breadth_tables`.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final

import numpy as np

from portfolio_edge.core._types import FloatArray
from portfolio_edge.inference.hac import hac_mean
from portfolio_edge.studies.overlay_growth import OverlayInputs, sharpe_admission_threshold

__all__ = [
    "MONTHS_PER_YEAR",
    "AdmissionVerdict",
    "PremiumEstimate",
    "admission",
    "average_pairwise_correlation",
    "common_window",
    "correlation_matrix",
    "decile_spread",
    "exact_effective_breadth",
    "minimum_detectable_effect",
    "normal_one_sided_p_value",
    "premium",
]

MONTHS_PER_YEAR: Final = 12

#: The equity factor families this programme set out to cover, transcribed from the
#: working plan that named them so that the denominator of every breadth claim lives in
#: the repository rather than in an untracked file. Five have been tested (value,
#: momentum, profitability, investment, size); the rest are the gap this module scores.
EQUITY_FACTOR_FAMILIES: Final[tuple[str, ...]] = (
    "value",
    "momentum",
    "quality",
    "profitability",
    "investment / conservative growth",
    "size",
    "size conditioned on quality or value",
    "low beta / defensive / low volatility",
    "multifactor integration",
    "shareholder yield and buybacks",
    "earnings revisions",
    "post-earnings-announcement drift",
    "accruals",
    "net issuance",
    "short-term reversal",
    "long-term reversal",
    "equal weighting",
    "international and emerging-market implementations",
)

#: One-sided 5% critical value and the 80%-power quantile, the same pair
#: :mod:`portfolio_edge.experiments.exp_010_marginal_sleeve_value` uses, so every
#: minimum detectable effect in this repository is on one scale.
_Z_ALPHA_ONE_SIDED_05: Final = 1.6448536269514722
_Z_POWER_80: Final = 0.8416212335729143
_Z_TWO_SIDED_95: Final = 1.959963984540054

#: ``|rho|`` above which equation (4) stops being a usable admission test. Taken
#: verbatim from :mod:`portfolio_edge.studies.overlay_growth`, which measured the
#: failure on a covered-call index at ``rho = 0.86``.
FIRST_ORDER_CORRELATION_LIMIT: Final = 0.5


def _as_series(returns: Sequence[float] | FloatArray) -> FloatArray:
    values = np.asarray(returns, dtype=np.float64)
    if values.ndim != 1:
        raise ValueError(f"returns must be one-dimensional, got shape {values.shape}")
    if values.size < 2:
        raise ValueError(f"need at least two observations, got {values.size}")
    if not np.all(np.isfinite(values)):
        raise ValueError(
            "returns contain a non-finite value. Missing months must be dropped by "
            "the caller, with the window it kept stated, rather than filled here."
        )
    return values


def minimum_detectable_effect(
    standard_error: float,
    *,
    z_alpha: float = _Z_ALPHA_ONE_SIDED_05,
    z_power: float = _Z_POWER_80,
) -> float:
    """``(z_{1-alpha} + z_power) * standard_error``, identical in form to exp_001/010.

    The smallest true effect a one-sided test of size ``alpha`` rejects the null for
    with probability ``power``. Reported beside every premium in this module because a
    null result from an instrument whose floor exceeds the bar carries no information,
    which is the whole content of
    [the resolution table](../../../../docs/research/evidence-base.md) §1.
    """
    if standard_error < 0.0:
        raise ValueError(f"standard_error must be non-negative, got {standard_error}")
    return (z_alpha + z_power) * standard_error


def normal_one_sided_p_value(t_statistic: float) -> float:
    """``P(Z > t)`` under the standard normal, for the alternative "premium > 0".

    One-sided to match the one-sided minimum detectable effect above; reporting a
    two-sided p-value beside a one-sided MDE would be two different tests in one row.
    The normal rather than the t distribution because every window here has at least
    seventy observations and the HAC standard error's own degrees of freedom are not
    the sample size anyway.
    """
    return 0.5 * math.erfc(t_statistic / math.sqrt(2.0))


@dataclass(frozen=True)
class PremiumEstimate:
    """One factor over one window, with everything needed to read the number.

    ``annualised_premium`` is the arithmetic monthly mean times twelve, not a
    geometric return: an admission test is about the first moment of an excess return
    stream, and compounding a long-short spread that is never funded would be a
    different claim.

    ``mde_80`` is the instrument's floor and ``interval`` its resolution. **A premium
    below its own MDE is not a small premium; it is an unresolved one**, and the
    ``resolved`` flag says which.
    """

    label: str
    months: int
    annualised_premium: float
    annualised_volatility: float
    hac_standard_error: float
    t_statistic: float
    p_value_one_sided: float
    interval_low: float
    interval_high: float
    mde_80: float
    sharpe: float

    @property
    def resolved(self) -> bool:
        """Whether the point estimate exceeds the window's own detection floor."""
        return self.annualised_premium > self.mde_80


def premium(
    returns: Sequence[float] | FloatArray,
    *,
    label: str,
    periods_per_year: int = MONTHS_PER_YEAR,
    n_lags: int | None = None,
) -> PremiumEstimate:
    """Annualised arithmetic premium, HAC interval, and the window's own MDE.

    The standard error is Newey-West with the automatic lag count from
    :mod:`portfolio_edge.inference.hac`, because monthly factor returns are serially
    dependent and an i.i.d. standard error understates the interval on exactly the
    series — reversal and momentum — where the dependence is the strategy.
    """
    values = _as_series(returns)
    estimate = hac_mean(values, n_lags=n_lags)
    scale = float(periods_per_year)
    annual_premium = scale * estimate.mean
    annual_error = scale * estimate.standard_error
    volatility = float(np.std(values, ddof=1)) * math.sqrt(scale)
    t_statistic = estimate.mean / estimate.standard_error if estimate.standard_error > 0 else 0.0
    return PremiumEstimate(
        label=label,
        months=int(values.size),
        annualised_premium=annual_premium,
        annualised_volatility=volatility,
        hac_standard_error=annual_error,
        t_statistic=t_statistic,
        p_value_one_sided=normal_one_sided_p_value(t_statistic),
        interval_low=annual_premium - _Z_TWO_SIDED_95 * annual_error,
        interval_high=annual_premium + _Z_TWO_SIDED_95 * annual_error,
        mde_80=minimum_detectable_effect(annual_error),
        sharpe=annual_premium / volatility if volatility > 0.0 else 0.0,
    )


@dataclass(frozen=True)
class AdmissionVerdict:
    """Equation (4) of :mod:`portfolio_edge.studies.overlay_growth`, scored.

    ``usable`` is the field that matters and it is not ``clears``. Above
    ``FIRST_ORDER_CORRELATION_LIMIT`` the first-order condition is a small difference
    of large numbers and mis-scores a sleeve that is mostly the base in disguise, so
    the verdict is withheld rather than reported as a pass or a fail.
    """

    label: str
    base_exposure: float
    correlation: float
    sharpe: float
    threshold: float
    margin: float
    clears: bool
    usable: bool


def admission(
    *,
    label: str,
    sharpe: float,
    correlation: float,
    base_volatility: float,
    base_exposure: float,
) -> AdmissionVerdict:
    """Score one candidate against ``S_d > L rho sigma_p`` at one base exposure.

    The threshold is delegated to
    :func:`portfolio_edge.studies.overlay_growth.sharpe_admission_threshold` rather
    than rewritten, so there is one definition of equation (4) in the repository. That
    function takes an ``OverlayInputs``, which carries expected returns this caller
    does not have and the threshold does not use; they are passed as zero and the
    volatility of the diversifier as one, because ``L rho sigma_p`` depends on none of
    the three.
    """
    if base_volatility <= 0.0:
        raise ValueError(f"base volatility must be positive, got {base_volatility}")
    if not -1.0 <= correlation <= 1.0:
        raise ValueError(f"correlation must lie in [-1, 1], got {correlation}")
    threshold = sharpe_admission_threshold(
        OverlayInputs(
            base_excess_return=0.0,
            base_volatility=base_volatility,
            diversifier_excess_return=0.0,
            diversifier_volatility=1.0,
            correlation=correlation,
        ),
        base_exposure=base_exposure,
    )
    return AdmissionVerdict(
        label=label,
        base_exposure=base_exposure,
        correlation=correlation,
        sharpe=sharpe,
        threshold=threshold,
        margin=sharpe - threshold,
        clears=sharpe > threshold,
        usable=abs(correlation) <= FIRST_ORDER_CORRELATION_LIMIT,
    )


def _matrix(series: Sequence[Sequence[float] | FloatArray]) -> FloatArray:
    if len(series) < 2:
        raise ValueError("need at least two series")
    rows = [_as_series(item) for item in series]
    lengths = {row.size for row in rows}
    if len(lengths) != 1:
        raise ValueError(
            f"series have different lengths {sorted(lengths)}; align them on a common "
            "window first and state the window, rather than correlating ragged data"
        )
    return np.vstack(rows)


def correlation_matrix(
    series: Sequence[Sequence[float] | FloatArray],
) -> tuple[tuple[float, ...], ...]:
    """Pearson correlations of already-aligned series, as a plain nested tuple.

    Aligned rather than pairwise-complete on purpose. A pairwise-complete matrix
    computed over different windows per cell is not guaranteed positive semi-definite,
    and :func:`portfolio_edge.studies.overlay_growth.effective_breadth` and the
    ``Sigma^-1 e`` solve beside it both assume it is.
    """
    values = _matrix(series)
    correlations = np.atleast_2d(np.corrcoef(values))
    return tuple(tuple(float(x) for x in row) for row in correlations)


def average_pairwise_correlation(matrix: Sequence[Sequence[float]]) -> float:
    """Mean of the strictly-upper-triangular entries.

    This is the ``rho_dd`` that
    :func:`portfolio_edge.studies.overlay_growth.effective_breadth` takes, and using
    the average is exactly the equicorrelated approximation that function documents.
    It is honest only when the off-diagonal entries are of similar size; when they are
    not, the average hides the pair that is really one engine, so the full matrix must
    be reported beside any breadth number derived from it.
    """
    size = len(matrix)
    if size < 2:
        raise ValueError("need at least two series")
    off_diagonal = [
        float(matrix[i][j]) for i in range(size) for j in range(i + 1, size)
    ]
    return sum(off_diagonal) / len(off_diagonal)


def exact_effective_breadth(matrix: Sequence[Sequence[float]]) -> float:
    """``1' R^-1 1``: effective breadth without the equicorrelated approximation.

    :func:`portfolio_edge.studies.overlay_growth.effective_breadth` collapses a whole
    correlation matrix to one average. That average is exactly what hides the pair
    that is really one engine, so this function computes the same quantity from the
    matrix itself.

    The derivation is one line from ``MultiOverlay``. With ``k`` overlays of identical
    edge ``e`` and identical volatility ``sigma_d``, ``Sigma = sigma_d**2 R`` and
    ``e_vec = e * 1``, so the peak growth gain ``e_vec' Sigma^-1 e_vec / 2`` equals
    ``(e**2 / (2 sigma_d**2)) * 1' R^-1 1``. The leading factor is the single-sleeve
    peak, so the multiplier is ``1' R^-1 1`` — and substituting the equicorrelated
    ``R`` recovers ``k / (1 + (k-1) rho_dd)`` exactly.

    **It is an upper bound on anything realisable and should be read as one.** The
    equal-edge assumption gives every sleeve the same expected return, the matrix is
    estimated, and inverting an estimated correlation matrix amplifies error without
    limit as it approaches singularity. A number materially above the count of
    genuinely distinct strategies is evidence about the estimate.
    """
    values = np.asarray(matrix, dtype=np.float64)
    size = values.shape[0]
    if values.ndim != 2 or values.shape[1] != size:
        raise ValueError(f"matrix must be square, got shape {values.shape}")
    smallest_eigenvalue = float(np.min(np.linalg.eigvalsh(values)))
    if smallest_eigenvalue <= 1e-10:
        raise ValueError(
            "the correlation matrix is singular to working precision, so effective "
            f"breadth is not defined for it (eigenvalue {smallest_eigenvalue:.3e}). "
            "Two of these series are the same series."
        )
    ones = np.ones(size, dtype=np.float64)
    return float(ones @ np.linalg.solve(values, ones))


def common_window(
    periods: Sequence[Sequence[str]],
) -> tuple[str, ...]:
    """The sorted period labels present in every one of ``periods``.

    Period labels are compared as strings, which is correct for the ``YYYY-MM`` labels
    :mod:`portfolio_edge.data.table` emits and would be wrong for anything else.
    """
    if not periods:
        raise ValueError("need at least one period sequence")
    shared = set(periods[0])
    for item in periods[1:]:
        shared &= set(item)
    return tuple(sorted(shared))


def decile_spread(
    low: Sequence[float] | FloatArray, high: Sequence[float] | FloatArray
) -> FloatArray:
    """``low - high``, the long-short spread of two sorted portfolio legs.

    Trivial arithmetic given a name because the *direction* is the part that gets it
    wrong. Accruals and net issuance both pay the LOW leg, the opposite convention to
    value and profitability, and this function makes the caller name which leg is long
    rather than infer it from a column position.
    """
    long_leg = _as_series(low)
    short_leg = _as_series(high)
    if long_leg.size != short_leg.size:
        raise ValueError("legs must be the same length")
    return long_leg - short_leg
