"""What happens when you stack many sleeves that each beat the benchmark 55% of the time.

The proposition this module scores, in the investor's own words: *"if you stack a ton of
strategies that are 55% likely to beat the market then you will beat the market."*

**It is conditionally true and conditionally false, and one number decides which.** The
arithmetic below is elementary and has no free parameters, so the whole disagreement
reduces to two measurable inputs — the correlation of the sleeves' *excess* returns, and
whether the sleeves are funded from the same capital or financed on top of it.

The three results, stated before the code that produces them.

**1. Probability tracks the information ratio, and the information ratio tracks
*effective* breadth, not sleeve count.** For sleeves with excess-return vector ``e``,
weights ``w`` and excess covariance ``Sigma``,

    IR = w'e / sqrt(w' Sigma w),      P(ahead after T years) = Phi(IR sqrt(T))

which is :mod:`portfolio_edge.studies.outperformance_horizon` with ``e/s`` renamed. For
``k`` sleeves of identical edge, identical tracking error and mutual correlation ``rho``,
``IR = IR_1 sqrt(k / (1 + (k-1) rho))`` — the *same* ``k / (1 + (k-1) rho)`` that
:func:`portfolio_edge.studies.overlay_growth.effective_breadth` already defines. So

    P_k = Phi( z_1 sqrt(effective breadth) ),    z_1 = Phi^-1(P_1).

**2. Stacking has a ceiling, and at realistic correlations it is close.** Effective
breadth converges to ``1/rho`` as ``k`` grows, so

    P_infinity = Phi( z_1 / sqrt(rho) )

**however many sleeves are stacked**. At ``P_1 = 0.55`` and ``rho = 0.4`` an infinite
stack reaches 0.578. The investor's intuition — that enough 55% bets compound into a
near-certainty — is the ``rho = 0`` limit of this expression and nothing else.

**3. Funding decides whether "stack" means add or average.** Under a fixed capital base
the weights sum to at most one, so portfolio edge is a weighted *average* of sleeve edges
and is bounded above by the single best sleeve — adding a sleeve raises effective breadth
and lowers mean edge at the same time. Under a financed overlay the weights are notional
and unconstrained, so portfolio edge is a *sum*. **The thesis is a statement about
overlays being applied to a substitution portfolio**, and
[capital efficiency](../../../../docs/research/capital-efficiency-and-breadth.md) already
measures the gap between the two funding rules at 2.44 pp/yr for a 100%-equity base.

Two things this module deliberately does not do. It does not estimate any premium: every
edge is an input, because the same repository that can resolve a correlation to two
decimals cannot sign most of these premia
([evidence base](../../../../docs/research/evidence-base.md) §1). And it never multiplies
a factor loading by a long-only capture fraction — the sleeve edges it consumes are built
by :mod:`portfolio_edge.studies.value_tilt`, which raises on that error.

Units throughout are **percentage points a year**, matching
:mod:`portfolio_edge.studies.value_tilt`: a 4.74 pp/yr premium is ``4.74``. Weights are
fractions. The one conversion is into
:mod:`portfolio_edge.studies.outperformance_horizon`, which works in basis points.

Nothing here reads market data; the caller supplies edges and a covariance matrix. The
measured tables are regenerated by :mod:`portfolio_edge.studies._stacking_tables`.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final

import numpy as np

from portfolio_edge.core._types import FloatArray
from portfolio_edge.studies.factor_breadth import exact_effective_breadth
from portfolio_edge.studies.outperformance_horizon import (
    probability_of_outperformance,
)
from portfolio_edge.studies.overlay_growth import effective_breadth

__all__ = [
    "BASIS_POINTS_PER_PERCENT",
    "FUNDING_RULES",
    "MDE_TO_STANDARD_ERROR",
    "MarginalVerdict",
    "Sleeve",
    "StackVerdict",
    "confidence_ceiling",
    "correlation_to_covariance",
    "effective_bets",
    "equicorrelated_probability",
    "marginal_contribution",
    "portfolio_edge_ceiling",
    "probability_from_information_ratio",
    "probability_with_parameter_uncertainty",
    "stack",
    "stacking_ceiling_probability",
]

#: The one unit conversion in this module. ``outperformance_horizon`` works in basis
#: points; everything here is in percentage points a year, as ``value_tilt`` is.
BASIS_POINTS_PER_PERCENT: Final = 100.0

#: ``z_{1-alpha} + z_power`` at the one-sided 5% size and 80% power this repository uses
#: everywhere. Dividing a published MDE80 by it recovers the standard error behind it,
#: which is how a premium's uncertainty enters :func:`probability_with_parameter_uncertainty`
#: without any page having to publish a second number.
MDE_TO_STANDARD_ERROR: Final = 1.6448536269514722 + 0.8416212335729143

#: The two funding rules, named so a caller cannot leave the choice implicit. They are
#: the same two :mod:`portfolio_edge.studies.overlay_growth` distinguishes, and the
#: charter requires the choice to be part of the hypothesis rather than a default.
FUNDING_RULES: Final[tuple[str, str]] = ("substitution", "overlay")


@dataclass(frozen=True)
class Sleeve:
    """One active position, measured against the benchmark the whole stack is measured against.

    ``weight`` is a fraction of portfolio capital under ``substitution`` funding and a
    fraction of notional under ``overlay`` funding. ``edge`` and ``tracking_error`` are
    both **per dollar of sleeve** and both in percentage points a year, so a sleeve's
    contribution to portfolio edge is ``weight * edge``.

    ``edge`` is an assumption or a measurement supplied by the caller; this module never
    estimates one. ``tracking_error`` is the standard deviation of the sleeve's return
    *minus the return of what it displaces* — not the sleeve's own volatility, and not a
    tracking error against a fitted replication.
    """

    label: str
    weight: float
    edge: float
    tracking_error: float

    def __post_init__(self) -> None:
        if self.tracking_error < 0.0:
            raise ValueError(
                f"{self.label}: tracking error cannot be negative, got {self.tracking_error}"
            )

    @property
    def information_ratio(self) -> float:
        """``edge / tracking_error``: the sleeve's own standalone information ratio.

        Independent of weight, which is the point: scaling a sleeve up or down changes
        how much it matters and not how likely it is to be ahead.
        """
        if self.tracking_error == 0.0:
            return math.inf if self.edge > 0 else (-math.inf if self.edge < 0 else 0.0)
        return self.edge / self.tracking_error


@dataclass(frozen=True)
class StackVerdict:
    """Everything one stack produces, so a caller cannot quote half of it.

    ``effective_bets`` is ``1' R^-1 1`` — the breadth available *at optimal weights and
    equal edges*, and an upper bound on anything realisable. ``breadth_used`` is the
    fraction of the achievable information ratio the actual weights and actual edges
    capture, ``(IR / IR_max)**2``. A stack can hold five sleeves, have five effective
    bets available, and use a fifth of them; reporting only the first number is how a
    ticker count gets dressed up as diversification.
    """

    count: int
    edge: float
    tracking_error: float
    information_ratio: float
    effective_bets: float
    maximum_information_ratio: float
    breadth_used: float

    def probability(self, horizon_years: float) -> float:
        """``Phi(IR sqrt(T))``: probability the stack is ahead of the benchmark at ``T``."""
        return probability_from_information_ratio(
            self.information_ratio, horizon_years=horizon_years
        )


@dataclass(frozen=True)
class MarginalVerdict:
    """What one candidate adds to a stack that already exists.

    The criterion is ``alpha_k / omega_k``, the candidate's edge net of what the sleeves
    already held supply, over the part of its tracking error they do not already carry:

        beta_k  = rho_kp * s_k / s_p
        alpha_k = e_k - beta_k * e_p
        omega_k = s_k * sqrt(1 - rho_kp**2)

    and the stack's information ratio combines in quadrature,
    ``IR_new**2 = IR_old**2 + (alpha_k / omega_k)**2``. Two consequences the standalone
    view cannot express, and both of them are the investor's own objection:

    * a sleeve with a **negative** standalone edge raises the stack's probability
      whenever ``beta_k`` is negative enough that ``alpha_k > 0``;
    * a sleeve with a positive standalone edge adds **nothing** when ``alpha_k = 0``,
      however good it looks alone.

    ``beta`` and ``residual_correlation`` are estimates with substantial uncertainty, and
    ``alpha`` is a small difference of two larger numbers, so a marginal verdict is less
    robust than the standalone figures it is built from.
    """

    label: str
    beta: float
    alpha: float
    residual_tracking_error: float
    appraisal_ratio: float
    information_ratio_before: float
    information_ratio_after: float

    @property
    def earns_its_place(self) -> bool:
        """Whether the candidate raises the stack's information ratio at all."""
        return self.appraisal_ratio > 0.0


def probability_from_information_ratio(
    information_ratio: float, *, horizon_years: float
) -> float:
    """``Phi(IR sqrt(T))``, delegated to :mod:`outperformance_horizon`.

    Delegated rather than rewritten so the repository has one definition of the
    probability of outperformance, and so this module inherits that one's warnings: the
    independence and constant-mean assumptions both flatter the answer, and treating the
    edge as known rather than estimated removes the dominant source of uncertainty. Read
    every probability here as an upper bound on attainable confidence.
    """
    if not horizon_years > 0:
        raise ValueError(f"horizon_years must be positive, got {horizon_years}")
    if information_ratio == 0.0:
        return 0.5
    if not math.isfinite(information_ratio):
        return 1.0 if information_ratio > 0 else 0.0
    return probability_of_outperformance(
        edge_bp=information_ratio * BASIS_POINTS_PER_PERCENT,
        tracking_error_bp=BASIS_POINTS_PER_PERCENT,
        horizon_years=horizon_years,
    )


def correlation_to_covariance(
    correlation: Sequence[Sequence[float]], tracking_errors: Sequence[float]
) -> FloatArray:
    """``diag(s) R diag(s)``, with the symmetry and unit-diagonal checks a caller forgets."""
    matrix = np.asarray(correlation, dtype=np.float64)
    scale = np.asarray(tracking_errors, dtype=np.float64)
    size = scale.size
    if matrix.shape != (size, size):
        raise ValueError(
            f"correlation must be {size} by {size} to match {size} tracking errors, "
            f"got shape {matrix.shape}"
        )
    if not np.allclose(matrix, matrix.T, atol=1e-12):
        raise ValueError("correlation matrix must be symmetric")
    if not np.allclose(np.diag(matrix), 1.0, atol=1e-9):
        raise ValueError("correlation matrix must have a unit diagonal")
    if np.any(scale < 0.0):
        raise ValueError("tracking errors cannot be negative")
    return np.asarray(matrix * np.outer(scale, scale), dtype=np.float64)


def effective_bets(correlation: Sequence[Sequence[float]]) -> float:
    """``1' R^-1 1``, delegated to :func:`factor_breadth.exact_effective_breadth`.

    Re-exported rather than reimplemented because the repository should have one
    definition of the quantity, and because that function carries the warning this one
    needs: it is an upper bound, it assumes every sleeve has the same edge, and a value
    materially above the number of genuinely distinct strategies is evidence about the
    correlation estimate rather than about the strategies.
    """
    return exact_effective_breadth(correlation)


def stack(
    sleeves: Sequence[Sleeve], correlation: Sequence[Sequence[float]]
) -> StackVerdict:
    """Score one stack: edge, tracking error, information ratio, breadth available and used.

    The funding rule is **not** an argument, because it enters through the weights: under
    substitution they are capital weights summing to at most one, under an overlay they
    are notional and unconstrained. :func:`portfolio_edge_ceiling` is where the two
    regimes differ arithmetically.
    """
    if len(sleeves) == 0:
        raise ValueError("cannot score an empty stack")
    weights = np.asarray([one.weight for one in sleeves], dtype=np.float64)
    edges = np.asarray([one.edge for one in sleeves], dtype=np.float64)
    errors = np.asarray([one.tracking_error for one in sleeves], dtype=np.float64)
    covariance = correlation_to_covariance(correlation, [float(one) for one in errors])

    portfolio_edge = float(weights @ edges)
    variance = float(weights @ covariance @ weights)
    if variance < 0.0:
        raise ValueError(
            f"the weighted tracking variance is negative ({variance:.3e}); the "
            "correlation matrix is not positive semi-definite"
        )
    tracking_error = math.sqrt(variance)
    ratio = portfolio_edge / tracking_error if tracking_error > 0 else 0.0

    smallest = float(np.min(np.linalg.eigvalsh(covariance)))
    if smallest <= 1e-12:
        raise ValueError(
            "the sleeve covariance matrix is singular to working precision, so the "
            f"maximum information ratio is not defined (eigenvalue {smallest:.3e}). "
            "Two of these sleeves are the same sleeve."
        )
    maximum = math.sqrt(float(edges @ np.linalg.solve(covariance, edges)))
    return StackVerdict(
        count=len(sleeves),
        edge=portfolio_edge,
        tracking_error=tracking_error,
        information_ratio=ratio,
        effective_bets=effective_bets(correlation),
        maximum_information_ratio=maximum,
        breadth_used=(ratio / maximum) ** 2 if maximum > 0 else 0.0,
    )


def equicorrelated_probability(
    *, single_probability: float, count: int, correlation: float
) -> float:
    """``Phi(z_1 sqrt(k / (1 + (k-1) rho)))``: the whole thesis in one line.

    ``single_probability`` is each sleeve's own probability of beating the benchmark over
    the same horizon; the horizon cancels, which is why it does not appear. The breadth
    factor is delegated to
    :func:`portfolio_edge.studies.overlay_growth.effective_breadth`.

    The result is exact under the stated equicorrelated model and holds under **either**
    funding rule, because scaling every weight by a constant changes edge and tracking
    error together and leaves the ratio alone. **Funding changes the size of the edge,
    not the probability** — which is the single most counter-intuitive consequence of the
    arithmetic and the reason a diluted tilt is no less likely to work, only less worth
    doing.
    """
    if not 0.0 < single_probability < 1.0:
        raise ValueError(
            f"single_probability must lie strictly in (0, 1), got {single_probability}"
        )
    breadth = effective_breadth(count=count, mutual_correlation=correlation)
    z = _inverse_normal_cdf(single_probability)
    return _normal_cdf(z * math.sqrt(breadth))


def stacking_ceiling_probability(
    *, single_probability: float, correlation: float
) -> float:
    """``Phi(z_1 / sqrt(rho))``: the limit of :func:`equicorrelated_probability` as ``k -> inf``.

    The number to put in front of anyone who believes stacking converges to certainty.
    At a positive mutual correlation the effective breadth of an infinite stack is
    ``1 / rho``, so no number of sleeves gets past this.

    Raises at ``rho <= 0``: at zero correlation the limit is 1 and quoting it would
    suggest an unlimited supply of genuinely independent 55% bets exists, which is the
    assumption the whole page is about.
    """
    if not 0.0 < single_probability < 1.0:
        raise ValueError(
            f"single_probability must lie strictly in (0, 1), got {single_probability}"
        )
    if correlation <= 0.0:
        raise ValueError(
            f"the ceiling is only finite at a positive mutual correlation, got "
            f"{correlation}. At rho <= 0 the limit is 1 and says nothing about markets."
        )
    if correlation > 1.0:
        raise ValueError(f"correlation must lie in (0, 1], got {correlation}")
    return _normal_cdf(_inverse_normal_cdf(single_probability) / math.sqrt(correlation))


def probability_with_parameter_uncertainty(
    *, edge: float, edge_standard_error: float, tracking_error: float, horizon_years: float
) -> float:
    """``Phi(e sqrt(T) / sqrt(tau**2 T + s**2))``: the edge estimated rather than known.

    :func:`probability_from_information_ratio` and every probability in
    :mod:`portfolio_edge.studies.outperformance_horizon` treat the edge as a known
    constant. It is not: it is an estimate with a standard error ``tau``, and the two
    uncertainties compound differently. Path noise accumulates as ``s**2 T`` and averages
    away; **an error in the mean accumulates as ``tau**2 T**2`` and does not**. Writing
    the cumulative relative log return as ``N(e T, tau**2 T**2 + s**2 T)`` and dividing
    through by ``T`` gives the expression above.

    The consequence is :func:`confidence_ceiling`: waiting longer stops helping. This is
    the second ceiling on the stacking thesis and the one that binds where correlation
    does not, because the repository can resolve a correlation to two decimals and cannot
    sign most of the premia those correlations relate
    ([evidence base](../../../../docs/research/evidence-base.md) §1).
    """
    if not horizon_years > 0:
        raise ValueError(f"horizon_years must be positive, got {horizon_years}")
    if edge_standard_error < 0.0:
        raise ValueError(
            f"edge_standard_error cannot be negative, got {edge_standard_error}"
        )
    if tracking_error < 0.0:
        raise ValueError(f"tracking_error cannot be negative, got {tracking_error}")
    variance = edge_standard_error**2 * horizon_years + tracking_error**2
    if variance <= 0.0:
        return 1.0 if edge > 0 else (0.0 if edge < 0 else 0.5)
    return _normal_cdf(edge * math.sqrt(horizon_years) / math.sqrt(variance))


def confidence_ceiling(*, edge: float, edge_standard_error: float) -> float:
    """``Phi(e / tau)``: the ``T -> inf`` limit of :func:`probability_with_parameter_uncertainty`.

    However long the investor waits, the probability of being ahead cannot exceed the
    probability that the edge is positive at all. A 30-year horizon does not convert an
    unsignable premium into a likely outcome; it converts it into a longer wait for the
    same coin flip.
    """
    if edge_standard_error <= 0.0:
        raise ValueError(
            "the ceiling is only meaningful for an estimated edge; got a standard error "
            f"of {edge_standard_error}. With a known edge the limit is 1 by construction."
        )
    return _normal_cdf(edge / edge_standard_error)


def portfolio_edge_ceiling(
    edges: Sequence[float], *, rule: str, total_weight: float = 1.0
) -> float:
    """The largest portfolio edge a set of sleeve edges can produce under one funding rule.

    Under ``substitution`` the weights are capital and sum to at most ``total_weight``,
    so the best attainable portfolio edge is ``total_weight * max(edges)``: **a weighted
    average, never a sum.** Adding a sixth sleeve to five cannot raise this and will
    normally lower it, because pro-rata funding shrinks every sleeve already held. That
    is the dilution arithmetic, and it has no statistical content at all.

    Under ``overlay`` the weights are notional, the constraint is not binding, and the
    edges add: ``total_weight`` is read as the notional per sleeve. Financing is not
    free — see
    [capital efficiency](../../../../docs/research/capital-efficiency-and-breadth.md)
    for the 2.44 pp/yr funding-rule gap and for what a wrapper keeps of it — but the
    *shape* of the arithmetic is a sum rather than an average, which is why the same
    intuition is right here and wrong above.
    """
    if rule not in FUNDING_RULES:
        raise ValueError(f"rule must be one of {FUNDING_RULES}, got {rule!r}")
    if len(edges) == 0:
        raise ValueError("need at least one sleeve edge")
    if total_weight < 0.0:
        raise ValueError(f"total_weight cannot be negative, got {total_weight}")
    if rule == "substitution":
        return total_weight * max(edges)
    return total_weight * sum(edges)


def marginal_contribution(
    *,
    label: str,
    candidate: Sleeve,
    held_edge: float,
    held_tracking_error: float,
    correlation_to_held: float,
) -> MarginalVerdict:
    """Score one candidate against the active portfolio already held.

    ``held_edge`` and ``held_tracking_error`` describe the *whole* existing active
    position — not one sleeve of it — and ``correlation_to_held`` is between the
    candidate's excess returns and that position's. ``candidate.weight`` is not used: the
    verdict is about direction, and the weight decides magnitude separately.
    """
    if not -1.0 <= correlation_to_held <= 1.0:
        raise ValueError(
            f"correlation must lie in [-1, 1], got {correlation_to_held}"
        )
    if held_tracking_error <= 0.0:
        raise ValueError(
            f"the held position's tracking error must be positive, got {held_tracking_error}"
        )
    if abs(correlation_to_held) == 1.0:
        raise ValueError(
            "a candidate perfectly correlated with what is already held has no residual "
            "and no marginal verdict: it is the same position at a different size"
        )
    beta = correlation_to_held * candidate.tracking_error / held_tracking_error
    alpha = candidate.edge - beta * held_edge
    residual = candidate.tracking_error * math.sqrt(1.0 - correlation_to_held**2)
    appraisal = alpha / residual if residual > 0 else 0.0
    before = held_edge / held_tracking_error
    return MarginalVerdict(
        label=label,
        beta=beta,
        alpha=alpha,
        residual_tracking_error=residual,
        appraisal_ratio=appraisal,
        information_ratio_before=before,
        information_ratio_after=math.copysign(
            math.sqrt(before**2 + appraisal**2), 1.0
        )
        if before >= 0
        else -math.sqrt(before**2 + appraisal**2),
    )


def _normal_cdf(x: float) -> float:
    return 0.5 * math.erfc(-x / math.sqrt(2.0))


def _inverse_normal_cdf(p: float) -> float:
    """Acklam's rational approximation, refined once by Halley on :func:`_normal_cdf`.

    Written out rather than imported so this module keeps the dependency profile of the
    rest of ``studies``: closed forms, ``math`` and ``numpy``. The Halley step takes the
    error to machine precision, which matters because the caller inverts a probability
    near 0.5 where the approximation is at its weakest in relative terms.
    """
    if not 0.0 < p < 1.0:
        raise ValueError(f"p must lie strictly in (0, 1), got {p}")
    a = (
        -3.969683028665376e01,
        2.209460984245205e02,
        -2.759285104469687e02,
        1.383577518672690e02,
        -3.066479806614716e01,
        2.506628277459239e00,
    )
    b = (
        -5.447609879822406e01,
        1.615858368580409e02,
        -1.556989798598866e02,
        6.680131188771972e01,
        -1.328068155288572e01,
    )
    c = (
        -7.784894002430293e-03,
        -3.223964580411365e-01,
        -2.400758277161838e00,
        -2.549732539343734e00,
        4.374664141464968e00,
        2.938163982698783e00,
    )
    d = (
        7.784695709041462e-03,
        3.224671290700398e-01,
        2.445134137142996e00,
        3.754408661907416e00,
    )
    low, high = 0.02425, 1.0 - 0.02425
    if p < low:
        q = math.sqrt(-2.0 * math.log(p))
        x = (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) / (
            (((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1.0
        )
    elif p <= high:
        q = p - 0.5
        r = q * q
        x = (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) * q / (
            ((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1.0
        )
    else:
        q = math.sqrt(-2.0 * math.log(1.0 - p))
        x = -(((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) / (
            (((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1.0
        )
    error = _normal_cdf(x) - p
    density = math.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)
    if density > 0.0:
        step = error / density
        x -= step / (1.0 + 0.5 * x * step)
    return x
