"""Render the frozen exp035 TAIL-versus-bills comparison without a new analysis."""

from __future__ import annotations

import json
import math
from pathlib import Path

import yaml

from portfolio_edge.reporting.live_fund_figures import signed

RUN_ID = "c9c0b898cf644ca0a2723d7ea0b02255"


def main() -> None:
    root = Path(__file__).resolve().parents[4]
    result = json.loads((root / "research" / "artifacts" / RUN_ID / "result.json").read_text())
    portfolio = result["result"]["diagnostics"]["portfolios"]["tail_long|12m|5bp"]
    comparison = portfolio["comparisons"]["TAIL vs bills"]
    years = len(portfolio["months"]) / 12
    ratio = comparison["terminal_wealth_ratio"]
    if not math.isclose(math.exp(comparison["log_gap_pp_yr"] / 100 * years), ratio, rel_tol=1e-12):
        raise ValueError("log growth and relative terminal wealth disagree")
    low, high = [
        signed(100 * math.expm1(endpoint / 100 * years))
        for endpoint in comparison["log_gap_interval"]
    ]
    record = {
        "label": "A 5% TAIL allocation compared with 5% in cash-like government bills",
        "value": signed(100 * (ratio - 1)),
        "unit": "ending wealth over the full period",
        "interval": f"95% interval [{low}, {high}]",
        "status": "exploratory",
        "asOf": "2026-09-05",
        "period": "February 2020 to March 2026",
        "source": {
            "label": "SEC fund returns and portfolio simulation",
            "docPath": "docs/research/alternative-sleeves-audit.md",
            "anchor": "funded-crash-hedge-comparison",
        },
        "note": (
            "Exploratory, February 2020 to March 2026. Both portfolios hold the same "
            "95% in US and international stocks and rebalance yearly. Fund returns include "
            "internal costs; investor trades cost an assumed 0.05% roundtrip. Taxes and a "
            "final sale are excluded. The interval describes uncertainty in this historical "
            "comparison, not the probability of a future gain."
        ),
    }
    output = root / "src" / "content" / "figures" / "live-tail-bills-wealth.yaml"
    output.write_text(
        "# Generated by portfolio_edge.reporting.crash_hedge_figures from exp035.\n"
        + yaml.safe_dump(record, sort_keys=False, allow_unicode=True, width=88)
    )
    print(output.relative_to(root))


if __name__ == "__main__":
    main()
