"""Render exp030's paired wealth differences; no new experiment or client arithmetic."""

from __future__ import annotations

import json
import math
from pathlib import Path

import yaml

RUN_ID = "785ca563fc554fbd862b2cc1b41bbc9f"
LABELS = {
    "avuv": "Replace the 15% VTV holding with AVUV",
    "spmo": "Move 5% of the portfolio from VTI to SPMO",
    "both": "Make both changes",
}


def signed(value: float) -> str:
    return f"{value:+.1f}%".replace("-", "\N{MINUS SIGN}")


def main() -> None:
    root = Path(__file__).resolve().parents[4]
    result_path = root / "research" / "artifacts" / RUN_ID / "result.json"
    result = json.loads(result_path.read_text())
    portfolio = result["result"]["diagnostics"]["portfolios"]["value-lean|5bp"]
    years = len(portfolio["months"]) / 12
    for arm, label in LABELS.items():
        comparison = portfolio["comparisons"][f"{arm} vs unchanged"]
        gap = comparison["log_gap_pp_yr"]
        ratio = comparison["terminal_wealth_ratio"]
        if not math.isclose(math.exp(gap / 100 * years), ratio, rel_tol=1e-12):
            raise ValueError("log growth and terminal wealth disagree")
        low, high = [
            signed(100 * math.expm1(endpoint / 100 * years))
            for endpoint in comparison["log_gap_interval"]
        ]
        record = {
            "label": label,
            "value": signed(100 * (ratio - 1)),
            "unit": "ending wealth versus the unchanged portfolio",
            "interval": f"[{low}, {high}]",
            "status": "exploratory",
            "asOf": "2026-09-05",
            "period": "October 2021 to March 2026",
            "source": {
                "label": "Fund filings and portfolio simulation",
                "docPath": "docs/research/final-construction-test.md",
                "anchor": "current-published-portfolios-funded-fund-substitutions",
            },
            "note": (
                "The portfolios start with cash and rebalance yearly. Fund returns already "
                "include fees and internal trading costs. We add an assumed 0.05% roundtrip "
                "cost for investor trades, including the initial purchase. Personal taxes "
                "and a final sale are excluded."
            ),
        }
        output = root / "src" / "content" / "figures" / f"live-value-{arm}-wealth.yaml"
        output.write_text(
            "# Generated by portfolio_edge.reporting.live_fund_figures from exp030.\n"
            + yaml.safe_dump(record, sort_keys=False, allow_unicode=True, width=88)
            + "\n"
        )
        print(output.relative_to(root))


if __name__ == "__main__":
    main()
