"""Render the state of the whole programme from the ledger, as Markdown.

Run with ``uv run python -m portfolio_edge.reporting.programme_status``.

This module exists because the same four counts -- entries, runs, distinct
specifications, experiment families -- were being maintained by hand in the
root ``README.md``, in the research framework and in decision 0004, and had
already drifted apart: one place said "33 ledgered executions of 15 distinct
specifications" while the ledger held 41 runs over 21 specifications. A number
narrated in three places is a number that will be wrong in at least one.

The ledger is the only thing that knows what was actually run, so it is the only
thing allowed to say. Prose links here; it does not restate.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Final

from portfolio_edge.experiments.ledger import (
    TRIALS_CAVEAT,
    Ledger,
    RunState,
    RunStatus,
    fold_runs,
    search_counts,
)
from portfolio_edge.experiments.result import ResultStatus

DEFAULT_LEDGER: Final = Path(__file__).resolve().parents[3] / "ledger.jsonl"

#: Ordered worst-to-best, so a reader scanning the table meets the rejections first.
_STATUS_ORDER: Final = (
    ResultStatus.REJECTED,
    ResultStatus.UNRESOLVED,
    ResultStatus.EXPLORATORY,
    ResultStatus.SOURCE_REPRODUCED,
    ResultStatus.INDEPENDENTLY_REPRODUCED,
    ResultStatus.WALK_FORWARD_TESTED,
    ResultStatus.SHADOW_LIVE,
    ResultStatus.PRODUCTION_ELIGIBLE,
)


def _terminal_statuses(states: Iterable[RunState]) -> dict[str, list[ResultStatus]]:
    """Every result status each family reached, deduplicated and ordered."""
    by_family: dict[str, set[ResultStatus]] = {}
    for state in states:
        if state.result_status is not None:
            by_family.setdefault(state.experiment_family, set()).add(state.result_status)
    return {
        family: sorted(found, key=_STATUS_ORDER.index)
        for family, found in sorted(by_family.items())
    }


def _counts_by_result(states: Iterable[RunState]) -> Mapping[ResultStatus, int]:
    counts: dict[ResultStatus, int] = {}
    for state in states:
        if state.result_status is not None:
            counts[state.result_status] = counts.get(state.result_status, 0) + 1
    return {status: counts[status] for status in _STATUS_ORDER if status in counts}


def render(ledger_path: Path = DEFAULT_LEDGER) -> str:
    """The programme's state as a Markdown fragment, computed from the ledger."""
    ledger = Ledger(ledger_path)
    entries = list(ledger.read())
    runs = fold_runs(entries)
    states = list(runs.values())
    counts = search_counts(entries)
    families = _terminal_statuses(states)
    by_result = _counts_by_result(states)

    unfinished = sum(
        1 for state in states if state.status in (RunStatus.FAILED, RunStatus.ABANDONED)
    )

    lines = [
        "<!-- Generated by `uv run python -m portfolio_edge.reporting.programme_status`.",
        "     Do not edit by hand; the ledger is the source of truth. -->",
        "",
        f"**{len(entries)} ledger entries · {counts.total_invocations} runs · "
        f"{counts.distinct_spec_hashes} distinct specifications · "
        f"{len(counts.distinct_spec_hashes_by_family)} experiment families.**",
        "",
        f"{counts.distinct_spec_hashes} is the number a deflated-Sharpe trial count starts "
        "from, and it is an upper bound.",
        "",
        "| Terminal status | Runs |",
        "| --- | ---: |",
    ]
    lines.extend(f"| `{status.value}` | {count} |" for status, count in by_result.items())
    lines.append(f"| no terminal status | {unfinished} |")
    lines.extend(
        [
            "",
            "| Experiment family | Specifications | Reached |",
            "| --- | ---: | --- |",
        ]
    )
    for family, statuses in families.items():
        specs = counts.distinct_spec_hashes_by_family.get(family, 0)
        reached = ", ".join(f"`{status.value}`" for status in statuses)
        lines.append(f"| `{family}` | {specs} | {reached} |")

    lines.extend(["", f"> {TRIALS_CAVEAT}"])
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER)
    args = parser.parse_args(argv)
    print(render(args.ledger), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
