"""The programme-status table is derived from the ledger, never narrated.

These tests pin the property that made the module worth writing: the counts come
from the file, so a hand-edited number in a document cannot silently disagree
with what was actually run.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from portfolio_edge.reporting.programme_status import DEFAULT_LEDGER, main, render


def _entry(
    *,
    run_id: str,
    family: str,
    event: str,
    spec_hash: str | None = "a" * 64,
    result_status: str | None = None,
) -> dict[str, object]:
    return {
        "schema_version": 1,
        "entry_id": f"{run_id}-{event}",
        "run_id": run_id,
        "experiment_family": family,
        "run_kind": "exploratory",
        "event": event,
        "status": event,
        "spec_hash": spec_hash,
        "seed": 1,
        "origin": "human",
        "parent_run_id": None,
        "consumes_final_holdout": False,
        "results_viewed": False,
        "result_status": result_status,
        "failure_reason": None,
        "artifacts": [],
        "timestamp_utc": "2026-01-01T00:00:00+00:00",
        "git_commit": None,
        "worktree_dirty": False,
        "code_version": "0",
        "environment": {},
        "parameters": {},
        "dataset_manifest_hashes": [],
        "diff_sha256": None,
        "notes": None,
    }


@pytest.fixture
def synthetic_ledger(tmp_path: Path) -> Path:
    path = tmp_path / "ledger.jsonl"
    entries = [
        _entry(run_id="r1", family="exp_x", event="started"),
        _entry(run_id="r1", family="exp_x", event="succeeded", result_status="rejected"),
        _entry(run_id="r2", family="exp_y", event="started", spec_hash="b" * 64),
        _entry(
            run_id="r2",
            family="exp_y",
            event="succeeded",
            spec_hash="b" * 64,
            result_status="exploratory",
        ),
        _entry(run_id="r3", family="exp_y", event="started", spec_hash="c" * 64),
        _entry(run_id="r3", family="exp_y", event="abandoned", spec_hash="c" * 64),
    ]
    path.write_text("\n".join(json.dumps(e) for e in entries) + "\n", encoding="utf-8")
    return path


def test_counts_come_from_the_file(synthetic_ledger: Path) -> None:
    rendered = render(synthetic_ledger)
    assert "**6 ledger entries · 3 runs · 3 distinct specifications · 2 experiment families.**" in (
        rendered
    )


def test_a_family_lists_every_status_it_reached(synthetic_ledger: Path) -> None:
    rendered = render(synthetic_ledger)
    assert "| `exp_x` | 1 | `rejected` |" in rendered
    assert "| `exp_y` | 2 | `exploratory` |" in rendered


def test_an_abandoned_run_has_no_terminal_status(synthetic_ledger: Path) -> None:
    assert "| no terminal status | 1 |" in render(synthetic_ledger)


def test_the_trials_caveat_travels_with_the_count(synthetic_ledger: Path) -> None:
    assert "UPPER BOUND" in render(synthetic_ledger)


def test_the_table_is_marked_generated(synthetic_ledger: Path) -> None:
    assert render(synthetic_ledger).startswith("<!-- Generated by")


def test_it_renders_the_repository_ledger() -> None:
    """The committed ledger renders, which is what the documents will quote."""
    assert DEFAULT_LEDGER.is_file(), DEFAULT_LEDGER
    rendered = render(DEFAULT_LEDGER)
    assert "experiment families" in rendered
    assert "phase1_ff_reproduction" in rendered


def test_main_writes_the_table(synthetic_ledger: Path, capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["--ledger", str(synthetic_ledger)]) == 0
    assert "ledger entries" in capsys.readouterr().out
